spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 88888888

logging:
 level:
   com.wang.start.dao: trace

mybatis-plus:
  mapper-locations:
    - com/wang/start/mapper/*.xml